language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# command to install dependencies
#install: "pip install -r requirements.txt"
install: "pip install ."
# command to run tests, e.g. python setup.py test
# command to run tests
script: nosetests
