#################################
# General setup
#################################
sudo: false
language: python

python:
  - "3.4"

notifications:
  email: false

#################################
# Build Lifecycle
#################################
install:
  - echo "-----install-----"
  - pip install --upgrade pip wheel
  - pip install -r dev-requirements.txt
  - pip install coveralls

script:
  - echo "-----script-----"
  - nosetests --with-cov --cov ci_setup_check --cov-config .coverage.rc --logging-level=INFO

# Calculate coverage
after_success:
  - echo "-----after_success-----"
  - coveralls

deploy:
  provider: pypi
  user: dougthor42
  server: https://testpypi.python.org/pypi
  distributions: "sdist bdist_wheel"
  on:
    tags: true
