language: python
sudo: required

python:
  - "2.7"

notifications:
  email: false

before_script:
  - curl http://apt.wxwidgets.org/key.asc | sudo apt-key add - 
  - echo "deb http://apt.wxwidgets.org/ Precise-wx main" | sudo tee -a /etc/apt/sources.list
  - echo "eb-src http://apt.wxwidgets.org/ Precise-wx main  " | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install python-wxgtk2.8 python-wxtools wx2.8-i18n

install:
  - pip install --upgrade pip
  - pip install -r dev-requirements.txt
  - pip install coveralls

script:
  #- coverage run -m ci_setup_check core.py test_core.py
  - nosetests --with-cov --cov ci_setup_check --cov-config .coverage.rc --logging-level=INFO
  #- nosetests --with-cov --cov ci_setup_check --logging-level=INFO

# Calculate coverage
after_success:
  #- coveralls --config_file .coverage.rc
  - coveralls

#addons:
#  artifacts: true
