language: python

python:
  - "2.7"

notifications:
  email: false

install:
  - pip install -r dev-requirements.txt
  - pip install coveralls

script:
  - nosetests --with-cov --cov ci_setup_check --cov-config .coveragerc --logging-level=INFO

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc