#################################
# General setup
#################################
language: python

sudo: false

python:
  - "3.4"

notifications:
  email: false

#################################
# Build Lifecycle
#################################
before_install:
  - echo "----- before_install -----"

  # print out some system info
  - uname -a
  - lscpu
  - cat /proc/version
  - cat /etc/*release*
  - lsb_release -a

install:
  - echo "----- install -----"
  # Make sure I'm in the correct directory after all that before_install crap
  - cd /home/travis/build/dougthor42/ci_setup_testing/

  # Start the install of everything
  - pip install --upgrade pip
  - pip install http://dougthor42.github.io/tools/wxPython-3.0.3-cp34-cp34m-linux_x86_64.whl
#  - pip install -r dev-requirements.txt
  - pip install coveralls
  - pip install green

before_script:
  - echo "----- before_script -----"

script:
  - echo "----- script -----"
  - green ci_setup_check -vv --run-coverage

after_success:
  - echo "----- after_success -----"

  # Send coverage information to coveralls.io
  - coveralls

after_failure:
  - echo "----- after_failure -----"

#################################
# Additional Items
#################################
#addons:
#  apt:
#    packages:
#      - libghc-gstreamer-dev
#      - libnotify
#
#      # For wxPython?
#      - dpkg-dev
#      - build-essential
#      - libwebkitgtk-dev
#      - libjpeg-dev
#      - libtiff-dev
#      - libgtk2.0-dev
#      - libsdl1.2-dev
#      - libgstreamer-plugins-base0.10-dev
#      - freeglut3
#      - freeglut3-dev
#      - libnotify-dev
