#################################
# General setup
#################################
language: python

#sudo: required
sudo: false

python:
  - "3.4"

notifications:
  email: false

#################################
# Build Lifecycle
#################################

before_install:
  - echo "----- before_install -----"

  # print out some system info
  - uname -a
  - lscpu
#  - free -ht       # doesn't like -h (human readable) :-(
  - echo "Free Memory (megabytes)"
  - free -mt
  - cat /proc/version
  - cat /etc/*release*
  - lsb_release -a

  # Installing wxPython Phoenix from snapshot
  # -------------------------------------------------------------------------
  # Download the source tarball
#  - wget http://wxpython.org/Phoenix/snapshot-builds/wxPython_Phoenix-3.0.3.dev1820+49a8884.tar.gz
#  - ls

  # extract it
#  - tar -xzf wxPython_Phoenix-3.0.3.dev1820+49a8884.tar.gz
#  - ls
#  - ls wxPython_Phoenix-3.0.3.dev1820+49a8884

  # Run the build script
#  - ls ./wxPython_Phoenix-3.0.3.dev1820+49a8884/
#  - cd ./wxPython_Phoenix-3.0.3.dev1820+49a8884
#  - ls
#  - ls ./sip

  # seperate commands for:
  #  1. travis doesn't halt if there's no output
  #  2. easier debugging.
  #  3. customize things like sudo
#  - python ./build.py --build_dir=../bld dox touch etg --nodoc sip build     # split out
#  - python ./build.py --build_dir=./bld dox
#  - python ./build.py --build_dir=./bld touch
#  - python ./build.py --build_dir=./bld etg --nodoc
#  - python ./build.py --build_dir=./bld build      # split into _wx and _py
#  - python ./build.py --build_dir=./bld build_wx

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Up to this point confirmed OK.
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#  - python ./build.py --build_dir=./bld build_py
#  - python ./build.py --build_dir=./bld test --verbose
#  - cd ..

  # -------------------------------------------------------------------------

  # Installing wxPython Phoenix from repo clone of 49a8884e7c
  # -------------------------------------------------------------------------
  - echo "Installing wxPython Phoenix from repo clone of 49a8884e7c"
  # Clone the repo (downloads entire history)
  - git clone --depth=50 --branch=master git://github.com/wxWidgets/Phoenix.git

  # Change to the directory
  - cd Phoenix

  # Have to get submodule wxWidgets. See README.rts:building-wxwidgets
  - git submodule init
  - git submodule update

  # Follow the same flow for building wxPython from source.
  - python ./build.py dox
  - python ./build.py build_wx --jobs=16
  - python ./build.py touch
  - python ./build.py etg --nodoc
  - python ./build.py sip
  - python ./build.py build_py --jobs=16
#  - python ./build.py --build_dir=./bld test --verbose

install:
  - echo "----- install -----"
  # Make sure I'm in the correct directory after all that before_install crap
  - cd /home/travis/build/dougthor42/ci_setup_testing/

  # Start the install of everything
  - pip install --upgrade pip
#  - pip install -r dev-requirements.txt
#  - pip install coveralls
#  - pip install wheel
#  - pip install numpy
#  - pip install --upgrade --pre --trusted-host wxpython.org -vvv -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix

before_script:
  - echo "----- before_script -----"

script:
  - echo "----- script -----"
#  - nosetests

after_success:
  - echo "----- after_success -----"
  - echo "----- Building a wxPython wheel -----"
  - cd Phoenix
  - ls
  - python setup.py bdist_wheel
  - ls
  - cd dist
  - ls

after_failure:
  - echo "----- after_failure -----"
  - ls -lh /home/travis/build/dougthor42/ci_setup_testing/Phoenix/
  - ls -lh /home/travis/build/dougthor42/ci_setup_testing/Phoenix/bin
#  - ls -lh /home/travis/build/dougthor42/ci_setup_testing/Phoenix/bin/sip-4.16.7-linux
#  - file /home/travis/build/dougthor42/ci_setup_testing/Phoenix/bin/sip-4.16.7-linux

#################################
# Additional Items
#################################
addons:
  apt:
    packages:
      - libghc-gstreamer-dev
      - libnotify

      # For wxPython?
      - dpkg-dev
      - build-essential
      - libwebkitgtk-dev
      - libjpeg-dev
      - libtiff-dev
      - libgtk2.0-dev
      - libsdl1.2-dev
      - libgstreamer-plugins-base0.10-dev
      - freeglut3
      - freeglut3-dev
      - libnotify-dev
