language: python
sudo: required

python:
  - "2.7"

notifications:
  email: false

before_script:
  #- apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
  #- sudo apt-add-repository 'deb http://repos.codelite.org/wx3.0.2/ubuntu/ precise universe'
  #- curl http://repos.codelite.org/wx3.0.2/ubuntu/ | sudo apt-key add - 
  #- echo "deb http://apt.wxwidgets.org/ Precise-wx main" | sudo tee -a /etc/apt/sources.list
  #- echo "deb-src http://apt.wxwidgets.org/ Precise-wx main  " | sudo tee -a /etc/apt/sources.list
  #- sudo apt-get update -qq
  #- sudo apt-get install python-wxgtk2.8 python-wxtools wx2.8-i18n
  - sudo apt-get install python-wxgtk2.8 python-wxtools wx2.8-doc wx2.8-examples wx2.8-headers wx2.8-i18n

install:
  - pip install --upgrade pip
  - pip install -r dev-requirements.txt
  - pip install coveralls

script:
  #- coverage run -m ci_setup_check core.py test_core.py
  - nosetests --with-cov --cov ci_setup_check --cov-config .coverage.rc --logging-level=INFO
  #- nosetests --with-cov --cov ci_setup_check --logging-level=INFO

# Calculate coverage
after_success:
  #- coveralls --config_file .coverage.rc
  - coveralls

#addons:
#  artifacts: true
