#################################
# General setup
#################################
sudo: false
language: python

python:
  - "2.7"

notifications:
  email: false

#################################
# Build Lifecycle
#################################
before_install:
  - echo "-----before_install-----"
  # figure out where we are
  - ls
  # download the source tarball
  - wget https://github.com/wxWidgets/wxPython/archive/wxPy-3.0.2.0.tar.gz
  # extract the tarbal
  - ls
  - tar -xzf wxPy-3.0.2.0.tar.gz
  - ls
  - ls wxPython-wxPy-3.0.2.0
  - cd wxPython-wxPy-3.0.2.0/wxPython
  - ls ./wx
  - ls ./wx/build
  - ls
  - ls ../
  # comment out --enable-mediactrl in ../configure
  - cat ../configure | grep enable-mediactrl
  - sed -i 's|--enable-mediactrl|#--enable-mediactrl|' ../configure
  - cat ../configure | grep enable-mediactrl

#  - cat ../make

  # replace one line in wxPythonFull.spec.in
#  - cat ./distrib/wxPythonFull.spec.in | grep mediactrl
#  - sed -i 's|%define mediactrl 1|%define mediactrl 0|' ./distrib/wxPythonFull.spec.in
#  - cat ./distrib/wxPythonFull.spec.in | grep mediactrl

  # start the build
  - python build-wxpython.py --build_dir=../bld --install

install:
  - echo "-----install-----"
#  - pip install --upgrade --trusted-host wxpython.org --pre -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix
  - pip install --upgrade pip
  - pip install -r dev-requirements.txt
  - pip install coveralls

before_script:
  - echo "-----before_script-----"

script:
  - echo "-----script-----"
  #- coverage run -m ci_setup_check core.py test_core.py
  - nosetests --with-cov --cov ci_setup_check --cov-config .coverage.rc --logging-level=INFO
  #- nosetests --with-cov --cov ci_setup_check --logging-level=INFO

# Calculate coverage
after_success:
  - echo "-----after_success-----"
  #- coveralls --config_file .coverage.rc
  - coveralls

after_failure:
  - echo "-----after_failure-----"

after_script:
  - echo "-----after_script-----"

# Optional Deployment Steps
#before_deploy:
#  - echo "-----before_deploy-----"
#
#deploy:
#  - echo "-----deploy-----"
#
#after_deploy:
#  - echo "-----after_deploy-----"

#################################
# Additional Items
#################################
addons:
  apt:
    packages:
      - libgstreamer0.10-0
      - libgstreamer-plugins-base0.10-0
      - gconf2
      - gconf2-common
      - libgconf-2-4
      - libgconf2-4
      - dpkg-dev
      - build-essential
      - libjpeg-dev
      - libgtk2.0-dev
      - libsdl1.2-dev

      # Disallowed packages
      - libghc-gstreamer-dev
#      - libgstreamer-plugins-base0.10-dev
#      - libtiff-dev

#  artifacts: true
