### ----------------------
### General Configuration
### ----------------------

environment:
  global:
    CMD_IN_ENV: ""

  PYPI_PASSWORD:
    secure: 8cUzxTdioPoDRaR96m4k5kxW5P9Y99rf6OBPQ4epQds=

  TEST_PYPI_PASSWORD:
    secure: PgOnGr6YPasjIE080QFGhQqUNy0AoIhkNM9Dqs9iQMo=

  matrix:
#    - PYTHON: "C:\\Python27"
#      PYTHON_VERSION: "2.7.8"
#      PYTHON_ARCH: "32"

#    - PYTHON: "C:\\Python27-x64"
#      PYTHON_VERSION: "2.7.8"
#      PYTHON_ARCH: "64"
#
#    - PYTHON: "C:\\Python33"
#      PYTHON_VERSION: "3.3.5"
#      PYTHON_ARCH: "32"
#
#    - PYTHON: "C:\\Python33-x64"
#      PYTHON_VERSION: "3.3.5"
#      PYTHON_ARCH: "64"

#   - PYTHON: "C:\\Python34"
#     PYTHON_VERSION: "3.4.3"
#     PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "64"

install:
  # Check that we have the expected version and architecture for Python
  - "%PYTHON%\\python.exe -m pip install --upgrade pip wheel"
  - "%PYTHON%\\python.exe -m pip install -r dev-requirements.txt"

build: off  # Not a C# project, build stuff at the test step instead.

test_script:
  # Build the compiled extension and run the project tests
  - "%PYTHON%\\python.exe -m nose ci_setup_check"

after_test:
  # if tests OK, create whl package
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

on_success:
  # Create the PyPI rc file.
  - echo [distutils]                                     > %USERPROFILE%\\.pypirc
  - echo index-servers=                                 >> %USERPROFILE%\\.pypirc
  - echo   pypi                                         >> %USERPROFILE%\\.pypirc
  - echo   testpypi                                     >> %USERPROFILE%\\.pypirc
  - echo [pypi]                                         >> %USERPROFILE%\\.pypirc
  - echo repository = https://pypi.python.org/pypi      >> %USERPROFILE%\\.pypirc
  - echo username = dougthor42                          >> %USERPROFILE%\\.pypirc
  - echo password = %PYPI_PASSWORD%                     >> %USERPROFILE%\\.pypirc
  - echo [testpypi]                                     >> %USERPROFILE%\\.pypirc
  - echo repository = https://testpypi.python.org/pypi  >> %USERPROFILE%\\.pypirc
  - echo username = dougthor42                          >> %USERPROFILE%\\.pypirc
  - echo password = %TEST_PYPI_PASSWORD%                >> %USERPROFILE%\\.pypirc

  - "%PYTHON%\\python.exe setup.py bdist_wheel"

  # Deploy only on tags.
  #- if "%APPVEYOR_REPO_TAG%"=="true" ( "%PYTHON%\\python.exe -m twine upload -r testpypi %APPVEYOR_BUILD_FOLDER%\\dist\\*.whl") else ( echo "Not deploying because not a tagged commit.")
  - "%PYTHON%\\python.exe -m twine upload -r testpypi dist\\*.whl"
